//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RDictEnumString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RDictEnumString() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Dictionary.RDictEnumString", typeof(RDictEnumString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 總是下載 的當地語系化字串。
        /// </summary>
        internal static string AM_AlwaysDL {
            get {
                return ResourceManager.GetString("AM_AlwaysDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉後刪除 的當地語系化字串。
        /// </summary>
        internal static string AM_DelAfterClose {
            get {
                return ResourceManager.GetString("AM_DelAfterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只下載一次 的當地語系化字串。
        /// </summary>
        internal static string AM_DLonce {
            get {
                return ResourceManager.GetString("AM_DLonce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Beta 的當地語系化字串。
        /// </summary>
        internal static string AU_ChannelBeta {
            get {
                return ResourceManager.GetString("AU_ChannelBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stable 的當地語系化字串。
        /// </summary>
        internal static string AU_ChannelStable {
            get {
                return ResourceManager.GetString("AU_ChannelStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查更新並下載 的當地語系化字串。
        /// </summary>
        internal static string AU_ModeCheckAndUpdate {
            get {
                return ResourceManager.GetString("AU_ModeCheckAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只檢查 的當地語系化字串。
        /// </summary>
        internal static string AU_ModeCheckOnly {
            get {
                return ResourceManager.GetString("AU_ModeCheckOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不檢查 的當地語系化字串。
        /// </summary>
        internal static string AU_ModeNone {
            get {
                return ResourceManager.GetString("AU_ModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查更新失敗。 的當地語系化字串。
        /// </summary>
        internal static string AU_StatusCheckFailed {
            get {
                return ResourceManager.GetString("AU_StatusCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未檢查。 的當地語系化字串。
        /// </summary>
        internal static string AU_StatusHaveNotChecked {
            get {
                return ResourceManager.GetString("AU_StatusHaveNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已經是最新版本。 的當地語系化字串。
        /// </summary>
        internal static string AU_StatusIsLatest {
            get {
                return ResourceManager.GetString("AU_StatusIsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無網路連線。 的當地語系化字串。
        /// </summary>
        internal static string AU_StatusNoConnection {
            get {
                return ResourceManager.GetString("AU_StatusNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有可用的更新！ 的當地語系化字串。
        /// </summary>
        internal static string AU_StatusUpdateAvailable {
            get {
                return ResourceManager.GetString("AU_StatusUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異常狀態 的當地語系化字串。
        /// </summary>
        internal static string BA_SeriesAbnormal {
            get {
                return ResourceManager.GetString("BA_SeriesAbnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 攻擊 的當地語系化字串。
        /// </summary>
        internal static string BA_SeriesAttack {
            get {
                return ResourceManager.GetString("BA_SeriesAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回復 的當地語系化字串。
        /// </summary>
        internal static string BA_SeriesHeal {
            get {
                return ResourceManager.GetString("BA_SeriesHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不明 的當地語系化字串。
        /// </summary>
        internal static string BA_SeriesNull {
            get {
                return ResourceManager.GetString("BA_SeriesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支援 的當地語系化字串。
        /// </summary>
        internal static string BA_SeriesSupport {
            get {
                return ResourceManager.GetString("BA_SeriesSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 イージス (防禦型) 的當地語系化字串。
        /// </summary>
        internal static string CT_Aegis {
            get {
                return ResourceManager.GetString("CT_Aegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 フォース (攻擊型) 的當地語系化字串。
        /// </summary>
        internal static string CT_Force {
            get {
                return ResourceManager.GetString("CT_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 マギウス (魔法型) 的當地語系化字串。
        /// </summary>
        internal static string CT_Magius {
            get {
                return ResourceManager.GetString("CT_Magius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 メビウス (平均型) 的當地語系化字串。
        /// </summary>
        internal static string CT_Mebius {
            get {
                return ResourceManager.GetString("CT_Mebius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (不明) 的當地語系化字串。
        /// </summary>
        internal static string CT_Null {
            get {
                return ResourceManager.GetString("CT_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 B 的當地語系化字串。
        /// </summary>
        internal static string DL_B {
            get {
                return ResourceManager.GetString("DL_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 位元組 的當地語系化字串。
        /// </summary>
        internal static string DL_BText {
            get {
                return ResourceManager.GetString("DL_BText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已取消下載作業。 的當地語系化字串。
        /// </summary>
        internal static string DL_DownloadCancelled {
            get {
                return ResourceManager.GetString("DL_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載失敗。 的當地語系化字串。
        /// </summary>
        internal static string DL_DownloadFailed {
            get {
                return ResourceManager.GetString("DL_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載中... 的當地語系化字串。
        /// </summary>
        internal static string DL_Downloading {
            get {
                return ResourceManager.GetString("DL_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載成功！ 的當地語系化字串。
        /// </summary>
        internal static string DL_DownloadSucceed {
            get {
                return ResourceManager.GetString("DL_DownloadSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 KB 的當地語系化字串。
        /// </summary>
        internal static string DL_KB {
            get {
                return ResourceManager.GetString("DL_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 千位元組 的當地語系化字串。
        /// </summary>
        internal static string DL_KBText {
            get {
                return ResourceManager.GetString("DL_KBText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MB 的當地語系化字串。
        /// </summary>
        internal static string DL_MB {
            get {
                return ResourceManager.GetString("DL_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 百萬位元組 的當地語系化字串。
        /// </summary>
        internal static string DL_MBText {
            get {
                return ResourceManager.GetString("DL_MBText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沒有網際網路連線。 的當地語系化字串。
        /// </summary>
        internal static string DL_NoConnection {
            get {
                return ResourceManager.GetString("DL_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 就緒。 的當地語系化字串。
        /// </summary>
        internal static string DL_Ready {
            get {
                return ResourceManager.GetString("DL_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BA 的當地語系化字串。
        /// </summary>
        internal static string DREG_BA {
            get {
                return ResourceManager.GetString("DREG_BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色資料 的當地語系化字串。
        /// </summary>
        internal static string DREG_Info {
            get {
                return ResourceManager.GetString("DREG_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隊長技 的當地語系化字串。
        /// </summary>
        internal static string DREG_LS {
            get {
                return ResourceManager.GetString("DREG_LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 火 的當地語系化字串。
        /// </summary>
        internal static string EL_Fire {
            get {
                return ResourceManager.GetString("EL_Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 水 的當地語系化字串。
        /// </summary>
        internal static string EL_Water {
            get {
                return ResourceManager.GetString("EL_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 風 的當地語系化字串。
        /// </summary>
        internal static string EL_Wind {
            get {
                return ResourceManager.GetString("EL_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 D 的當地語系化字串。
        /// </summary>
        internal static string LG_Debug {
            get {
                return ResourceManager.GetString("LG_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 E 的當地語系化字串。
        /// </summary>
        internal static string LG_Error {
            get {
                return ResourceManager.GetString("LG_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 I 的當地語系化字串。
        /// </summary>
        internal static string LG_Info {
            get {
                return ResourceManager.GetString("LG_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 S 的當地語系化字串。
        /// </summary>
        internal static string LG_Status {
            get {
                return ResourceManager.GetString("LG_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 W 的當地語系化字串。
        /// </summary>
        internal static string LG_Warning {
            get {
                return ResourceManager.GetString("LG_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 獸種 的當地語系化字串。
        /// </summary>
        internal static string MS_Animal {
            get {
                return ResourceManager.GetString("MS_Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 昆蟲種 的當地語系化字串。
        /// </summary>
        internal static string MS_Bug {
            get {
                return ResourceManager.GetString("MS_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 龍種 的當地語系化字串。
        /// </summary>
        internal static string MS_Dragon {
            get {
                return ResourceManager.GetString("MS_Dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不死種 的當地語系化字串。
        /// </summary>
        internal static string MS_Ghost {
            get {
                return ResourceManager.GetString("MS_Ghost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 亞人種 的當地語系化字串。
        /// </summary>
        internal static string MS_HalfMan {
            get {
                return ResourceManager.GetString("MS_HalfMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人種 的當地語系化字串。
        /// </summary>
        internal static string MS_Human {
            get {
                return ResourceManager.GetString("MS_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幻異種 的當地語系化字串。
        /// </summary>
        internal static string MS_Phantom {
            get {
                return ResourceManager.GetString("MS_Phantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 植物種 的當地語系化字串。
        /// </summary>
        internal static string MS_Plant {
            get {
                return ResourceManager.GetString("MS_Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HP 的當地語系化字串。
        /// </summary>
        internal static string PR_HP {
            get {
                return ResourceManager.GetString("PR_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 INT 的當地語系化字串。
        /// </summary>
        internal static string PR_INT {
            get {
                return ResourceManager.GetString("PR_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MEN 的當地語系化字串。
        /// </summary>
        internal static string PR_MEN {
            get {
                return ResourceManager.GetString("PR_MEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SS 的當地語系化字串。
        /// </summary>
        internal static string PR_SS {
            get {
                return ResourceManager.GetString("PR_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 STR 的當地語系化字串。
        /// </summary>
        internal static string PR_STR {
            get {
                return ResourceManager.GetString("PR_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VIT 的當地語系化字串。
        /// </summary>
        internal static string PR_VIT {
            get {
                return ResourceManager.GetString("PR_VIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ALL 的當地語系化字串。
        /// </summary>
        internal static string SC_ALL {
            get {
                return ResourceManager.GetString("SC_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ALO 的當地語系化字串。
        /// </summary>
        internal static string SC_ALO {
            get {
                return ResourceManager.GetString("SC_ALO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GGO 的當地語系化字串。
        /// </summary>
        internal static string SC_GGO {
            get {
                return ResourceManager.GetString("SC_GGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SAO 的當地語系化字串。
        /// </summary>
        internal static string SC_SAO {
            get {
                return ResourceManager.GetString("SC_SAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 極上 的當地語系化字串。
        /// </summary>
        internal static string SP_R1 {
            get {
                return ResourceManager.GetString("SP_R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最上 的當地語系化字串。
        /// </summary>
        internal static string SP_R2 {
            get {
                return ResourceManager.GetString("SP_R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上品 的當地語系化字串。
        /// </summary>
        internal static string SP_R3 {
            get {
                return ResourceManager.GetString("SP_R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 良品 的當地語系化字串。
        /// </summary>
        internal static string SP_R4 {
            get {
                return ResourceManager.GetString("SP_R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 女性 的當地語系化字串。
        /// </summary>
        internal static string SX_Female {
            get {
                return ResourceManager.GetString("SX_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 男性 的當地語系化字串。
        /// </summary>
        internal static string SX_Male {
            get {
                return ResourceManager.GetString("SX_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 五 的當地語系化字串。
        /// </summary>
        internal static string WD_Fri {
            get {
                return ResourceManager.GetString("WD_Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一 的當地語系化字串。
        /// </summary>
        internal static string WD_Mon {
            get {
                return ResourceManager.GetString("WD_Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 六 的當地語系化字串。
        /// </summary>
        internal static string WD_Sat {
            get {
                return ResourceManager.GetString("WD_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日 的當地語系化字串。
        /// </summary>
        internal static string WD_Sun {
            get {
                return ResourceManager.GetString("WD_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 四 的當地語系化字串。
        /// </summary>
        internal static string WD_Thu {
            get {
                return ResourceManager.GetString("WD_Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 二 的當地語系化字串。
        /// </summary>
        internal static string WD_Tue {
            get {
                return ResourceManager.GetString("WD_Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 三 的當地語系化字串。
        /// </summary>
        internal static string WD_Wed {
            get {
                return ResourceManager.GetString("WD_Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 片手斧 的當地語系化字串。
        /// </summary>
        internal static string WP_1HAxe {
            get {
                return ResourceManager.GetString("WP_1HAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 片手長柄 的當地語系化字串。
        /// </summary>
        internal static string WP_1HMace {
            get {
                return ResourceManager.GetString("WP_1HMace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 片手劍 的當地語系化字串。
        /// </summary>
        internal static string WP_1HSword {
            get {
                return ResourceManager.GetString("WP_1HSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兩手斧 的當地語系化字串。
        /// </summary>
        internal static string WP_2HAxe {
            get {
                return ResourceManager.GetString("WP_2HAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兩手長柄 的當地語系化字串。
        /// </summary>
        internal static string WP_2HMace {
            get {
                return ResourceManager.GetString("WP_2HMace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兩手劍 的當地語系化字串。
        /// </summary>
        internal static string WP_2HSword {
            get {
                return ResourceManager.GetString("WP_2HSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 弓 的當地語系化字串。
        /// </summary>
        internal static string WP_Bow {
            get {
                return ResourceManager.GetString("WP_Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 短劍 的當地語系化字串。
        /// </summary>
        internal static string WP_Dagger {
            get {
                return ResourceManager.GetString("WP_Dagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 二刀流 的當地語系化字串。
        /// </summary>
        internal static string WP_DualSword {
            get {
                return ResourceManager.GetString("WP_DualSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銃 的當地語系化字串。
        /// </summary>
        internal static string WP_Gun {
            get {
                return ResourceManager.GetString("WP_Gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刀 的當地語系化字串。
        /// </summary>
        internal static string WP_Katana {
            get {
                return ResourceManager.GetString("WP_Katana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 細劍 的當地語系化字串。
        /// </summary>
        internal static string WP_Rapier {
            get {
                return ResourceManager.GetString("WP_Rapier", resourceCulture);
            }
        }
    }
}
