//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Controls {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RBaDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RBaDisplay() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Controls.RBaDisplay", typeof(RBaDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 BA1 的當地語系化字串。
        /// </summary>
        internal static string Layout_BA1 {
            get {
                return ResourceManager.GetString("Layout_BA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BA2 的當地語系化字串。
        /// </summary>
        internal static string Layout_BA2 {
            get {
                return ResourceManager.GetString("Layout_BA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BA3 的當地語系化字串。
        /// </summary>
        internal static string Layout_BA3 {
            get {
                return ResourceManager.GetString("Layout_BA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 治癒量 的當地語系化字串。
        /// </summary>
        internal static string Layout_HealRate {
            get {
                return ResourceManager.GetString("Layout_HealRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BA威力 的當地語系化字串。
        /// </summary>
        internal static string Layout_Power {
            get {
                return ResourceManager.GetString("Layout_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 % 的當地語系化字串。
        /// </summary>
        internal static string Layout_Rate {
            get {
                return ResourceManager.GetString("Layout_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分 的當地語系化字串。
        /// </summary>
        internal static string Layout_ScoreText {
            get {
                return ResourceManager.GetString("Layout_ScoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系 的當地語系化字串。
        /// </summary>
        internal static string Layout_Series {
            get {
                return ResourceManager.GetString("Layout_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 + 的當地語系化字串。
        /// </summary>
        internal static string Layout_SeriesAnd {
            get {
                return ResourceManager.GetString("Layout_SeriesAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 戰技(BA, Battle Ability) 的當地語系化字串。
        /// </summary>
        internal static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異常狀態 的當地語系化字串。
        /// </summary>
        internal static string Series_Abnormal {
            get {
                return ResourceManager.GetString("Series_Abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 攻擊 的當地語系化字串。
        /// </summary>
        internal static string Series_Attack {
            get {
                return ResourceManager.GetString("Series_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回復 的當地語系化字串。
        /// </summary>
        internal static string Series_Heal {
            get {
                return ResourceManager.GetString("Series_Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 支援 的當地語系化字串。
        /// </summary>
        internal static string Series_Support {
            get {
                return ResourceManager.GetString("Series_Support", resourceCulture);
            }
        }
    }
}
