//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Controls {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RBasicInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RBasicInfo() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Controls.RBasicInfo", typeof(RBasicInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 角色ID 的當地語系化字串。
        /// </summary>
        internal static string Layout_CharaID {
            get {
                return ResourceManager.GetString("Layout_CharaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 點選圖片以瀏覽大圖或下載圖片 的當地語系化字串。
        /// </summary>
        internal static string Layout_ClickToSeePicture {
            get {
                return ResourceManager.GetString("Layout_ClickToSeePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CV 的當地語系化字串。
        /// </summary>
        internal static string Layout_CV {
            get {
                return ResourceManager.GetString("Layout_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 屬性 的當地語系化字串。
        /// </summary>
        internal static string Layout_Element {
            get {
                return ResourceManager.GetString("Layout_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 英文名稱 的當地語系化字串。
        /// </summary>
        internal static string Layout_ENName {
            get {
                return ResourceManager.GetString("Layout_ENName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 俗名 的當地語系化字串。
        /// </summary>
        internal static string Layout_Folkname {
            get {
                return ResourceManager.GetString("Layout_Folkname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 獲得方法 的當地語系化字串。
        /// </summary>
        internal static string Layout_GetMethod {
            get {
                return ResourceManager.GetString("Layout_GetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色簡介(日文) 的當地語系化字串。
        /// </summary>
        internal static string Layout_Intro {
            get {
                return ResourceManager.GetString("Layout_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星級 的當地語系化字串。
        /// </summary>
        internal static string Layout_Rarity {
            get {
                return ResourceManager.GetString("Layout_Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 釋出日期 的當地語系化字串。
        /// </summary>
        internal static string Layout_ReleaseDate {
            get {
                return ResourceManager.GetString("Layout_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舞台 的當地語系化字串。
        /// </summary>
        internal static string Layout_Scene {
            get {
                return ResourceManager.GetString("Layout_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 性別 的當地語系化字串。
        /// </summary>
        internal static string Layout_Sex {
            get {
                return ResourceManager.GetString("Layout_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 武器 的當地語系化字串。
        /// </summary>
        internal static string Layout_Weapon {
            get {
                return ResourceManager.GetString("Layout_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未知 的當地語系化字串。
        /// </summary>
        internal static string Output_Unknown {
            get {
                return ResourceManager.GetString("Output_Unknown", resourceCulture);
            }
        }
    }
}
