//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Controls {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RParamI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RParamI() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Controls.RParamI", typeof(RParamI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 COST 的當地語系化字串。
        /// </summary>
        internal static string Layout_CostText {
            get {
                return ResourceManager.GetString("Layout_CostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數分布 的當地語系化字串。
        /// </summary>
        internal static string Layout_Distribution {
            get {
                return ResourceManager.GetString("Layout_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HP 的當地語系化字串。
        /// </summary>
        internal static string Layout_GrowRateHP {
            get {
                return ResourceManager.GetString("Layout_GrowRateHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 x 的當地語系化字串。
        /// </summary>
        internal static string Layout_GrowRateMultiplication {
            get {
                return ResourceManager.GetString("Layout_GrowRateMultiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數 的當地語系化字串。
        /// </summary>
        internal static string Layout_GrowRateParams {
            get {
                return ResourceManager.GetString("Layout_GrowRateParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成長倍率 的當地語系化字串。
        /// </summary>
        internal static string Layout_GrowRateText {
            get {
                return ResourceManager.GetString("Layout_GrowRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色等級與狀態 的當地語系化字串。
        /// </summary>
        internal static string Layout_Level {
            get {
                return ResourceManager.GetString("Layout_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已覺醒  的當地語系化字串。
        /// </summary>
        internal static string Layout_LevelAwaked {
            get {
                return ResourceManager.GetString("Layout_LevelAwaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lv1 的當地語系化字串。
        /// </summary>
        internal static string Layout_LevelLv1 {
            get {
                return ResourceManager.GetString("Layout_LevelLv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LvMAX 的當地語系化字串。
        /// </summary>
        internal static string Layout_LevelLvMAX {
            get {
                return ResourceManager.GetString("Layout_LevelLvMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未覺醒  的當地語系化字串。
        /// </summary>
        internal static string Layout_LevelUnawaked {
            get {
                return ResourceManager.GetString("Layout_LevelUnawaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HP 的當地語系化字串。
        /// </summary>
        internal static string Layout_ParamHP {
            get {
                return ResourceManager.GetString("Layout_ParamHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 INT 的當地語系化字串。
        /// </summary>
        internal static string Layout_ParamINT {
            get {
                return ResourceManager.GetString("Layout_ParamINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本質參數 的當地語系化字串。
        /// </summary>
        internal static string Layout_ParamMain {
            get {
                return ResourceManager.GetString("Layout_ParamMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MEN 的當地語系化字串。
        /// </summary>
        internal static string Layout_ParamMEN {
            get {
                return ResourceManager.GetString("Layout_ParamMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 STR 的當地語系化字串。
        /// </summary>
        internal static string Layout_ParamSTR {
            get {
                return ResourceManager.GetString("Layout_ParamSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VIT 的當地語系化字串。
        /// </summary>
        internal static string Layout_ParamVIT {
            get {
                return ResourceManager.GetString("Layout_ParamVIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 フォース (攻擊型) 的當地語系化字串。
        /// </summary>
        internal static string Layout_TypeAttack {
            get {
                return ResourceManager.GetString("Layout_TypeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 メビウス (平均型) 的當地語系化字串。
        /// </summary>
        internal static string Layout_TypeAverage {
            get {
                return ResourceManager.GetString("Layout_TypeAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 イージス (防禦型) 的當地語系化字串。
        /// </summary>
        internal static string Layout_TypeDefense {
            get {
                return ResourceManager.GetString("Layout_TypeDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 マギウス (魔法型) 的當地語系化字串。
        /// </summary>
        internal static string Layout_TypeMagius {
            get {
                return ResourceManager.GetString("Layout_TypeMagius", resourceCulture);
            }
        }
    }
}
