//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class UserConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserConfig defaultInstance = ((UserConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserConfig())));
        
        public static UserConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AU_ProgramMode {
            get {
                return ((int)(this["AU_ProgramMode"]));
            }
            set {
                this["AU_ProgramMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SE_BGMMute {
            get {
                return ((bool)(this["SE_BGMMute"]));
            }
            set {
                this["SE_BGMMute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AU_ProgramChannel {
            get {
                return ((int)(this["AU_ProgramChannel"]));
            }
            set {
                this["AU_ProgramChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SE/Feedback.SAO.Click.wav")]
        public string SE_Beep {
            get {
                return ((string)(this["SE_Beep"]));
            }
            set {
                this["SE_Beep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SE/Notify.SAO.System.wav")]
        public string SE_Warning {
            get {
                return ((string)(this["SE_Warning"]));
            }
            set {
                this["SE_Warning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SE/ソウルワーカー(Soul Worker) BGM - STEEL GRAVE.mp3")]
        public string SE_BGM {
            get {
                return ((string)(this["SE_BGM"]));
            }
            set {
                this["SE_BGM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SE_WarningMute {
            get {
                return ((bool)(this["SE_WarningMute"]));
            }
            set {
                this["SE_WarningMute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_Download {
            get {
                return ((string)(this["Path_Download"]));
            }
            set {
                this["Path_Download"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SE_BeepMute {
            get {
                return ((bool)(this["SE_BeepMute"]));
            }
            set {
                this["SE_BeepMute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
            set {
                this["DebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool State_AutoLoad {
            get {
                return ((bool)(this["State_AutoLoad"]));
            }
            set {
                this["State_AutoLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AU_CSVMode {
            get {
                return ((int)(this["AU_CSVMode"]));
            }
            set {
                this["AU_CSVMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SE/Popup.SAO.Message.wav")]
        public string SE_Message {
            get {
                return ((string)(this["SE_Message"]));
            }
            set {
                this["SE_Message"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SE_MessageMute {
            get {
                return ((bool)(this["SE_MessageMute"]));
            }
            set {
                this["SE_MessageMute"] = value;
            }
        }
    }
}
