//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RMain() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.RMain", typeof(RMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 角色資訊(+HTML輸出) 的當地語系化字串。
        /// </summary>
        internal static string AtPage_CharacterData {
            get {
                return ResourceManager.GetString("AtPage_CharacterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 csv內容一覽 的當地語系化字串。
        /// </summary>
        internal static string AtPage_CsvTable {
            get {
                return ResourceManager.GetString("AtPage_CsvTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案下載 的當地語系化字串。
        /// </summary>
        internal static string AtPage_Download {
            get {
                return ResourceManager.GetString("AtPage_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 裝備資訊 的當地語系化字串。
        /// </summary>
        internal static string AtPage_Equip {
            get {
                return ResourceManager.GetString("AtPage_Equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 經驗計算器 的當地語系化字串。
        /// </summary>
        internal static string AtPage_EXPCalc {
            get {
                return ResourceManager.GetString("AtPage_EXPCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        internal static string AtPage_HomePage {
            get {
                return ResourceManager.GetString("AtPage_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SAOCR Data Manager 的當地語系化字串。
        /// </summary>
        internal static string AtPage_ProgramName {
            get {
                return ResourceManager.GetString("AtPage_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 的當地語系化字串。
        /// </summary>
        internal static string AtPage_Settings {
            get {
                return ResourceManager.GetString("AtPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 各項統計資料 的當地語系化字串。
        /// </summary>
        internal static string AtPage_Statistics {
            get {
                return ResourceManager.GetString("AtPage_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網頁製作(裝備) 的當地語系化字串。
        /// </summary>
        internal static string AtPage_WebPageChara {
            get {
                return ResourceManager.GetString("AtPage_WebPageChara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網頁製作(角色) 的當地語系化字串。
        /// </summary>
        internal static string AtPage_WebPageEquip {
            get {
                return ResourceManager.GetString("AtPage_WebPageEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BA Dictionary 的當地語系化字串。
        /// </summary>
        internal static string DataTable_BADictionary {
            get {
                return ResourceManager.GetString("DataTable_BADictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Character Dimensions 的當地語系化字串。
        /// </summary>
        internal static string DataTable_CharaDimensions {
            get {
                return ResourceManager.GetString("DataTable_CharaDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Character Series 的當地語系化字串。
        /// </summary>
        internal static string DataTable_CharaSeries {
            get {
                return ResourceManager.GetString("DataTable_CharaSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LS Dictionary 的當地語系化字串。
        /// </summary>
        internal static string DataTable_LSDictionary {
            get {
                return ResourceManager.GetString("DataTable_LSDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 截圖 的當地語系化字串。
        /// </summary>
        internal static string Layout_Capture {
            get {
                return ResourceManager.GetString("Layout_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢視日誌 的當地語系化字串。
        /// </summary>
        internal static string Layout_CheckLog {
            get {
                return ResourceManager.GetString("Layout_CheckLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢視程式公告 的當地語系化字串。
        /// </summary>
        internal static string Layout_CheckProgramAnnouncements {
            get {
                return ResourceManager.GetString("Layout_CheckProgramAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉 的當地語系化字串。
        /// </summary>
        internal static string Layout_CloseProg {
            get {
                return ResourceManager.GetString("Layout_CloseProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 縮小 的當地語系化字串。
        /// </summary>
        internal static string Layout_Minimum {
            get {
                return ResourceManager.GetString("Layout_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開啟截圖資料夾 的當地語系化字串。
        /// </summary>
        internal static string Layout_ViewCaptureFolder {
            get {
                return ResourceManager.GetString("Layout_ViewCaptureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已擷取目前的資料庫圖像。 的當地語系化字串。
        /// </summary>
        internal static string Log_Captured {
            get {
                return ResourceManager.GetString("Log_Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已儲存目前的資料庫圖像。儲存時間:  的當地語系化字串。
        /// </summary>
        internal static string Log_CaptureSaved {
            get {
                return ResourceManager.GetString("Log_CaptureSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查更新完成。檢查結果: 的當地語系化字串。
        /// </summary>
        internal static string Log_CheckComplete {
            get {
                return ResourceManager.GetString("Log_CheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查更新中... 的當地語系化字串。
        /// </summary>
        internal static string Log_CheckingUpdate {
            get {
                return ResourceManager.GetString("Log_CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發生錯誤。 的當地語系化字串。
        /// </summary>
        internal static string Log_Error {
            get {
                return ResourceManager.GetString("Log_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 前往頁面:  的當地語系化字串。
        /// </summary>
        internal static string Log_GoToPage {
            get {
                return ResourceManager.GetString("Log_GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告！ 的當地語系化字串。
        /// </summary>
        internal static string Log_Warning {
            get {
                return ResourceManager.GetString("Log_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要關閉資料庫程式嗎？ 的當地語系化字串。
        /// </summary>
        internal static string Warning_Close {
            get {
                return ResourceManager.GetString("Warning_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉確認 的當地語系化字串。
        /// </summary>
        internal static string Warning_CloseTitle {
            get {
                return ResourceManager.GetString("Warning_CloseTitle", resourceCulture);
            }
        }
    }
}
