//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Message {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RStatus() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Message.RStatus", typeof(RStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 讀取資料中...... 的當地語系化字串。
        /// </summary>
        internal static string Acting_Loading {
            get {
                return ResourceManager.GetString("Acting_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查更新中... 的當地語系化字串。
        /// </summary>
        internal static string Action_CheckingUpdate {
            get {
                return ResourceManager.GetString("Action_CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未查詢到指定的欄位。請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Error_DataNotFound {
            get {
                return ResourceManager.GetString("Error_DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先匯入csv檔案再跳轉。 的當地語系化字串。
        /// </summary>
        internal static string Error_DataNotInput {
            get {
                return ResourceManager.GetString("Error_DataNotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未輸入參數陣列。 的當地語系化字串。
        /// </summary>
        internal static string Error_EmptyParameterArray {
            get {
                return ResourceManager.GetString("Error_EmptyParameterArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發生例外狀況。訊息:  的當地語系化字串。
        /// </summary>
        internal static string Error_Exception1 {
            get {
                return ResourceManager.GetString("Error_Exception1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  種類: 的當地語系化字串。
        /// </summary>
        internal static string Error_Exception2 {
            get {
                return ResourceManager.GetString("Error_Exception2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 。 的當地語系化字串。
        /// </summary>
        internal static string Error_Exception3 {
            get {
                return ResourceManager.GetString("Error_Exception3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 找不到BA字典檔。請重新選擇。 的當地語系化字串。
        /// </summary>
        internal static string Error_FileNotFoundBADict {
            get {
                return ResourceManager.GetString("Error_FileNotFoundBADict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 找不到csv檔案。請重新選擇。 的當地語系化字串。
        /// </summary>
        internal static string Error_FileNotFoundCSV {
            get {
                return ResourceManager.GetString("Error_FileNotFoundCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入檔案格式錯誤。請重新選擇檔案。 的當地語系化字串。
        /// </summary>
        internal static string Error_FileNotLegal {
            get {
                return ResourceManager.GetString("Error_FileNotLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先輸入關鍵字後再搜尋。 的當地語系化字串。
        /// </summary>
        internal static string Error_KeywordEmpty {
            get {
                return ResourceManager.GetString("Error_KeywordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先匯入BA字典檔。 的當地語系化字串。
        /// </summary>
        internal static string Error_NeedToInputBADict {
            get {
                return ResourceManager.GetString("Error_NeedToInputBADict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先匯入csv。 的當地語系化字串。
        /// </summary>
        internal static string Error_NeedToInputCSV {
            get {
                return ResourceManager.GetString("Error_NeedToInputCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始欄位不得大於終點欄位。請重新輸入搜尋目標欄位。 的當地語系化字串。
        /// </summary>
        internal static string Error_StartIsBiggerThanEnd {
            get {
                return ResourceManager.GetString("Error_StartIsBiggerThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束欄位不得小於起始欄位，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Error_WrongColumnNumber {
            get {
                return ResourceManager.GetString("Error_WrongColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查更新失敗。狀態:  的當地語系化字串。
        /// </summary>
        internal static string Result_CheckUpdateFailed {
            get {
                return ResourceManager.GetString("Result_CheckUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查更新完成。狀態:  的當地語系化字串。
        /// </summary>
        internal static string Result_CheckUpdateSucceed {
            get {
                return ResourceManager.GetString("Result_CheckUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BA資料預載未完成。 的當地語系化字串。
        /// </summary>
        internal static string Result_DataBADictPreloadInCompleted {
            get {
                return ResourceManager.GetString("Result_DataBADictPreloadInCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 csv預載未完成。 的當地語系化字串。
        /// </summary>
        internal static string Result_DataCSVPreloadInCompleted {
            get {
                return ResourceManager.GetString("Result_DataCSVPreloadInCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料預載完成。 的當地語系化字串。
        /// </summary>
        internal static string Result_DataPreloadCompleted {
            get {
                return ResourceManager.GetString("Result_DataPreloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 csv解壓縮完成。檔案位於匯入的assetbundle的目錄底下。csv路徑已自動登錄。 的當地語系化字串。
        /// </summary>
        internal static string Result_DisunityComplete {
            get {
                return ResourceManager.GetString("Result_DisunityComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 根據關鍵字&quot; 的當地語系化字串。
        /// </summary>
        internal static string Result_FoundString1 {
            get {
                return ResourceManager.GetString("Result_FoundString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &quot;，找到了 的當地語系化字串。
        /// </summary>
        internal static string Result_FoundString2 {
            get {
                return ResourceManager.GetString("Result_FoundString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個結果。 的當地語系化字串。
        /// </summary>
        internal static string Result_FoundString3 {
            get {
                return ResourceManager.GetString("Result_FoundString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已匯入assetbundle檔案。 路徑: 的當地語系化字串。
        /// </summary>
        internal static string Result_ImportAssetbundleComplete {
            get {
                return ResourceManager.GetString("Result_ImportAssetbundleComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已匯入csv檔案。 路徑: 的當地語系化字串。
        /// </summary>
        internal static string Result_ImportCsvComplete {
            get {
                return ResourceManager.GetString("Result_ImportCsvComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料讀取完畢。 的當地語系化字串。
        /// </summary>
        internal static string Result_LoadingComplete {
            get {
                return ResourceManager.GetString("Result_LoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 按鍵音已更換。 路徑: 的當地語系化字串。
        /// </summary>
        internal static string Result_SEChangedBeep {
            get {
                return ResourceManager.GetString("Result_SEChangedBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警示音已更換。 路徑: 的當地語系化字串。
        /// </summary>
        internal static string Result_SEChangedWarning {
            get {
                return ResourceManager.GetString("Result_SEChangedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定已儲存。 的當地語系化字串。
        /// </summary>
        internal static string Result_SettingsSaved {
            get {
                return ResourceManager.GetString("Result_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 就緒。 的當地語系化字串。
        /// </summary>
        internal static string Result_Standby {
            get {
                return ResourceManager.GetString("Result_Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未找到資料。 的當地語系化字串。
        /// </summary>
        internal static string Result_StringNotFound {
            get {
                return ResourceManager.GetString("Result_StringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態代碼 0xF0027000\n\n檔案下載的儲存路徑已更動。更動後的路徑為:  的當地語系化字串。
        /// </summary>
        internal static string S_0xF0027000 {
            get {
                return ResourceManager.GetString("S_0xF0027000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態代碼 0xF0027001\n\n資源重新讀取完畢。 的當地語系化字串。
        /// </summary>
        internal static string S_0xF0027001 {
            get {
                return ResourceManager.GetString("S_0xF0027001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已達到搜尋資料的最末端。 的當地語系化字串。
        /// </summary>
        internal static string Warning_EndOfSerachResult {
            get {
                return ResourceManager.GetString("Warning_EndOfSerachResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未匯入任何資源(.assetbundle)或資料(.csv)檔。 的當地語系化字串。
        /// </summary>
        internal static string Warning_FileNotImported {
            get {
                return ResourceManager.GetString("Warning_FileNotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先讀取csv檔案後，再尋找資料位置。 的當地語系化字串。
        /// </summary>
        internal static string Warning_ReadCsvFirst {
            get {
                return ResourceManager.GetString("Warning_ReadCsvFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請檢查副檔名是否正確。 的當地語系化字串。
        /// </summary>
        internal static string Warning_ReCheckExtension {
            get {
                return ResourceManager.GetString("Warning_ReCheckExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 音效未更動。 的當地語系化字串。
        /// </summary>
        internal static string Warning_SENotChanged {
            get {
                return ResourceManager.GetString("Warning_SENotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 副檔名錯誤。 的當地語系化字串。
        /// </summary>
        internal static string Warning_WrongExtension {
            get {
                return ResourceManager.GetString("Warning_WrongExtension", resourceCulture);
            }
        }
    }
}
