//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Message {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RWarning {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RWarning() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Message.RWarning", typeof(RWarning).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000001\n\n主資料表的資料行數需大於或等於副資料表。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000001 {
            get {
                return ResourceManager.GetString("W_0xC0000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000002\n\n無法查詢到合乎條件的結果。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000002 {
            get {
                return ResourceManager.GetString("W_0xC0000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000003\n\n已超過搜尋結果的最末端。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000003 {
            get {
                return ResourceManager.GetString("W_0xC0000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000004\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000004 {
            get {
                return ResourceManager.GetString("W_0xC0000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000005\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000005 {
            get {
                return ResourceManager.GetString("W_0xC0000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000006\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000006 {
            get {
                return ResourceManager.GetString("W_0xC0000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000007 {
            get {
                return ResourceManager.GetString("W_0xC0000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000008 {
            get {
                return ResourceManager.GetString("W_0xC0000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0000009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0000009 {
            get {
                return ResourceManager.GetString("W_0xC0000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002000\n\n請先選擇要下載圖片的角色，再將其新增至下載清單。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002000 {
            get {
                return ResourceManager.GetString("W_0xC0002000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002001\n\n請先選擇要從下載清單移除的角色。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002001 {
            get {
                return ResourceManager.GetString("W_0xC0002001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002002\n\n搜尋結果的清單不能為空。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002002 {
            get {
                return ResourceManager.GetString("W_0xC0002002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002003\n\n找不到角色，請確認輸入的ID是否正確，並且此角色已存在。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002003 {
            get {
                return ResourceManager.GetString("W_0xC0002003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002004\n\n請先提供關鍵字、星級，或是角色系代碼再搜尋角色。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002004 {
            get {
                return ResourceManager.GetString("W_0xC0002004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002005\n\n此角色已經新增到下載清單中了。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002005 {
            get {
                return ResourceManager.GetString("W_0xC0002005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002006\n\n找不到要開啟的檔案，該檔案可能因為下載不完全或取消下載的後續作業而被刪除了。\n檔案路徑:  的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002006 {
            get {
                return ResourceManager.GetString("W_0xC0002006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002007\n\n無網際網路連線。請先連線至網路後再下載圖片。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002007 {
            get {
                return ResourceManager.GetString("W_0xC0002007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002008 {
            get {
                return ResourceManager.GetString("W_0xC0002008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0002009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0002009 {
            get {
                return ResourceManager.GetString("W_0xC0002009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0003001\n\n傳入的隊長技參數目錄有誤，故傳回的值為null。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0003001 {
            get {
                return ResourceManager.GetString("W_0xC0003001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0003002\n\n傳入的參數種類有誤，故傳回的值為null。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0003002 {
            get {
                return ResourceManager.GetString("W_0xC0003002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0003003\n\n傳入的星期有誤，故傳回的值為null。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0003003 {
            get {
                return ResourceManager.GetString("W_0xC0003003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0003003\n\n傳入的日誌種類有誤，故傳回的值為null。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0003004 {
            get {
                return ResourceManager.GetString("W_0xC0003004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004000\n\n根據提供的關鍵字，沒有找到相關的結果。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004000 {
            get {
                return ResourceManager.GetString("W_0xC0004000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004001\n\n您所提供的關鍵字中有不合法的字元，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004001 {
            get {
                return ResourceManager.GetString("W_0xC0004001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004002\n\n請先提供要搜尋的關鍵字、角色星級，或是角色系代碼再搜尋角色。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004002 {
            get {
                return ResourceManager.GetString("W_0xC0004002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004003\n\n請先匯入帶有角色相關資料的資料表再搜尋角色。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004003 {
            get {
                return ResourceManager.GetString("W_0xC0004003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004004\n\n請先匯入帶有角色系代碼查閱表的資料表再開啟視窗。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004004 {
            get {
                return ResourceManager.GetString("W_0xC0004004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004005\n\n請檢查匯入的資源是否全部都不為null。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004005 {
            get {
                return ResourceManager.GetString("W_0xC0004005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004006\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004006 {
            get {
                return ResourceManager.GetString("W_0xC0004006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004007 {
            get {
                return ResourceManager.GetString("W_0xC0004007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004008 {
            get {
                return ResourceManager.GetString("W_0xC0004008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0004009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0004009 {
            get {
                return ResourceManager.GetString("W_0xC0004009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005000\n\nAssetbundle解壓縮失敗。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005000 {
            get {
                return ResourceManager.GetString("W_0xC0005000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005001\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005001 {
            get {
                return ResourceManager.GetString("W_0xC0005001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005002\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005002 {
            get {
                return ResourceManager.GetString("W_0xC0005002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005003\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005003 {
            get {
                return ResourceManager.GetString("W_0xC0005003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005004\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005004 {
            get {
                return ResourceManager.GetString("W_0xC0005004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005005\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005005 {
            get {
                return ResourceManager.GetString("W_0xC0005005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005006\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005006 {
            get {
                return ResourceManager.GetString("W_0xC0005006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005007 {
            get {
                return ResourceManager.GetString("W_0xC0005007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005008 {
            get {
                return ResourceManager.GetString("W_0xC0005008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0005009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0005009 {
            get {
                return ResourceManager.GetString("W_0xC0005009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007001\n\n角色ID長度不正確，請重新確認。角色ID由8位數字組成。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007001 {
            get {
                return ResourceManager.GetString("W_0xC0007001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007002\n\n查詢標的資料表沒有內容。請嘗試重新載入資源檔。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007002 {
            get {
                return ResourceManager.GetString("W_0xC0007002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007003\n\n角色ID不能為空，請重新輸入。角色ID由8位數字組成。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007003 {
            get {
                return ResourceManager.GetString("W_0xC0007003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007004\n\n傳入的參數起始堆棧為空。請檢察資源檔是否載入。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007004 {
            get {
                return ResourceManager.GetString("W_0xC0007004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007005。\n\n角色ID不存在，請重新檢查輸入的ID是否正確。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007005 {
            get {
                return ResourceManager.GetString("W_0xC0007005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007006\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007006 {
            get {
                return ResourceManager.GetString("W_0xC0007006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007007 {
            get {
                return ResourceManager.GetString("W_0xC0007007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007008 {
            get {
                return ResourceManager.GetString("W_0xC0007008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0007009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0007009 {
            get {
                return ResourceManager.GetString("W_0xC0007009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A001\n\n角色ID長度不正確，請重新確認。角色ID由8位數字組成。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A001 {
            get {
                return ResourceManager.GetString("W_0xC000A001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A002\n\n查詢標的資料表沒有內容。請嘗試重新載入資源檔。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A002 {
            get {
                return ResourceManager.GetString("W_0xC000A002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A003\n\n角色ID不能為空，請重新輸入。角色ID由8位數字組成。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A003 {
            get {
                return ResourceManager.GetString("W_0xC000A003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A004\n\n傳入的參數起始堆棧為空。請檢察資源檔是否載入。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A004 {
            get {
                return ResourceManager.GetString("W_0xC000A004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A005\n\n角色ID不存在，請重新檢查輸入的ID是否正確。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A005 {
            get {
                return ResourceManager.GetString("W_0xC000A005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A006\n\n本質參數的參數種類有誤。只有可能是STR、VIT、INT、MEN。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A006 {
            get {
                return ResourceManager.GetString("W_0xC000A006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A007 {
            get {
                return ResourceManager.GetString("W_0xC000A007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A008 {
            get {
                return ResourceManager.GetString("W_0xC000A008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000A009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000A009 {
            get {
                return ResourceManager.GetString("W_0xC000A009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E001\n\n角色ID長度不正確，請重新確認。角色ID由8位數字組成。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E001 {
            get {
                return ResourceManager.GetString("W_0xC000E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E002\n\n查詢標的資料表沒有內容。請嘗試重新載入資源檔。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E002 {
            get {
                return ResourceManager.GetString("W_0xC000E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E003\n\n角色ID不能為空，請重新輸入。角色ID由8位數字組成。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E003 {
            get {
                return ResourceManager.GetString("W_0xC000E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E004\n\n傳入的參數起始堆棧為空。請檢察資源檔是否載入。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E004 {
            get {
                return ResourceManager.GetString("W_0xC000E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E005\n\n傳入的BA起始堆棧為空。請檢察資源檔是否載入。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E005 {
            get {
                return ResourceManager.GetString("W_0xC000E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E006\n\n角色ID不存在，請重新檢查輸入的ID是否正確。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E006 {
            get {
                return ResourceManager.GetString("W_0xC000E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E007 {
            get {
                return ResourceManager.GetString("W_0xC000E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E008 {
            get {
                return ResourceManager.GetString("W_0xC000E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC000E009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC000E009 {
            get {
                return ResourceManager.GetString("W_0xC000E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011001\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011001 {
            get {
                return ResourceManager.GetString("W_0xC0011001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011002\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011002 {
            get {
                return ResourceManager.GetString("W_0xC0011002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011003\n\n請先開啟至少一個頁籤再查詢角色資料。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011003 {
            get {
                return ResourceManager.GetString("W_0xC0011003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011004\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011004 {
            get {
                return ResourceManager.GetString("W_0xC0011004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011005\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011005 {
            get {
                return ResourceManager.GetString("W_0xC0011005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011006\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011006 {
            get {
                return ResourceManager.GetString("W_0xC0011006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011007 {
            get {
                return ResourceManager.GetString("W_0xC0011007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011008 {
            get {
                return ResourceManager.GetString("W_0xC0011008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0011009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0011009 {
            get {
                return ResourceManager.GetString("W_0xC0011009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013001\n\n傳入的角色舞台有誤，顏色未改變。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013001 {
            get {
                return ResourceManager.GetString("W_0xC0013001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013002\n\n傳入的性別有誤，顏色未改變。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013002 {
            get {
                return ResourceManager.GetString("W_0xC0013002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013003\n\n傳入的屬性有誤，顏色未改變。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013003 {
            get {
                return ResourceManager.GetString("W_0xC0013003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013004\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013004 {
            get {
                return ResourceManager.GetString("W_0xC0013004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013005\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013005 {
            get {
                return ResourceManager.GetString("W_0xC0013005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013006\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013006 {
            get {
                return ResourceManager.GetString("W_0xC0013006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013007 {
            get {
                return ResourceManager.GetString("W_0xC0013007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013008 {
            get {
                return ResourceManager.GetString("W_0xC0013008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0013009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0013009 {
            get {
                return ResourceManager.GetString("W_0xC0013009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0015001\n\n儲存檔名不能為空，請重新輸入檔名。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0015001 {
            get {
                return ResourceManager.GetString("W_0xC0015001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0019001\n\n因傳入的角色資料登記為未成功載入，故顯示作業以中斷。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0019001 {
            get {
                return ResourceManager.GetString("W_0xC0019001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0019002\n\n登記最愛未成功。無法在資料表中找到對應的欄位。角色ID:  的當地語系化字串。
        /// </summary>
        internal static string W_0xC0019002 {
            get {
                return ResourceManager.GetString("W_0xC0019002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC001B001\n\n根據提供的關鍵字，沒有找到相關的結果。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC001B001 {
            get {
                return ResourceManager.GetString("W_0xC001B001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023000\n\n傳入的下載模組為空，請先指定下載模組後在使用下載樣式的訊息方塊。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023000 {
            get {
                return ResourceManager.GetString("W_0xC0023000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023001\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023001 {
            get {
                return ResourceManager.GetString("W_0xC0023001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023002\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023002 {
            get {
                return ResourceManager.GetString("W_0xC0023002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023003\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023003 {
            get {
                return ResourceManager.GetString("W_0xC0023003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023004\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023004 {
            get {
                return ResourceManager.GetString("W_0xC0023004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023005\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023005 {
            get {
                return ResourceManager.GetString("W_0xC0023005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023006\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023006 {
            get {
                return ResourceManager.GetString("W_0xC0023006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023007\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023007 {
            get {
                return ResourceManager.GetString("W_0xC0023007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023008\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023008 {
            get {
                return ResourceManager.GetString("W_0xC0023008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0023009\n\n 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0023009 {
            get {
                return ResourceManager.GetString("W_0xC0023009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0025000\n\n傳入的路徑是資料夾而非檔案。請重新確認。路徑: 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0025000 {
            get {
                return ResourceManager.GetString("W_0xC0025000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0025001\n\n傳入的檔案來源有誤，應為本地或是網路。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0025001 {
            get {
                return ResourceManager.GetString("W_0xC0025001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0027000\n\n檔案下載的儲存路徑未更動。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0027000 {
            get {
                return ResourceManager.GetString("W_0xC0027000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0027001\n\n確定要清除所有已下載的附件嗎？ 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0027001 {
            get {
                return ResourceManager.GetString("W_0xC0027001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC0027002\n\n發生錯誤，清除附件失敗。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC0027002 {
            get {
                return ResourceManager.GetString("W_0xC0027002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告代碼 0xC002B001\n\n在武器特效字典中找不到對應的翻譯，故目前以日文顯示。 的當地語系化字串。
        /// </summary>
        internal static string W_0xC002B001 {
            get {
                return ResourceManager.GetString("W_0xC002B001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告 的當地語系化字串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
