//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Module {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RDownloader {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RDownloader() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Module.RDownloader", typeof(RDownloader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 非同步下載作業開始。URL:  的當地語系化字串。
        /// </summary>
        internal static string Log_ASyncDownload1 {
            get {
                return ResourceManager.GetString("Log_ASyncDownload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，儲存路徑:  的當地語系化字串。
        /// </summary>
        internal static string Log_ASyncDownload2 {
            get {
                return ResourceManager.GetString("Log_ASyncDownload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載取消。 的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadCancelled {
            get {
                return ResourceManager.GetString("Log_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載失敗。 的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadFailed {
            get {
                return ResourceManager.GetString("Log_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載成功。項目數量:  的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadSucceed1 {
            get {
                return ResourceManager.GetString("Log_DownloadSucceed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，平均速度:  的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadSucceed2 {
            get {
                return ResourceManager.GetString("Log_DownloadSucceed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除下載不完整的檔案的作業失敗，正在重試...檔案完整路徑:  的當地語系化字串。
        /// </summary>
        internal static string Log_RetryToDelete {
            get {
                return ResourceManager.GetString("Log_RetryToDelete", resourceCulture);
            }
        }
    }
}
