//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RCharaData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RCharaData() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Forms.RCharaData", typeof(RCharaData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        internal static string Layout_CharaIDGo {
            get {
                return ResourceManager.GetString("Layout_CharaIDGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色ID 的當地語系化字串。
        /// </summary>
        internal static string Layout_CharaIDText {
            get {
                return ResourceManager.GetString("Layout_CharaIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的最愛角色 的當地語系化字串。
        /// </summary>
        internal static string Layout_FavoriteText {
            get {
                return ResourceManager.GetString("Layout_FavoriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 製作角色圖片、ID對照表 的當地語系化字串。
        /// </summary>
        internal static string Layout_MakeIDTable {
            get {
                return ResourceManager.GetString("Layout_MakeIDTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 要求顯示角色資料，角色ID:  的當地語系化字串。
        /// </summary>
        internal static string Log_RequestCharacter {
            get {
                return ResourceManager.GetString("Log_RequestCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示角色資料，角色ID:  的當地語系化字串。
        /// </summary>
        internal static string Log_ShowCharacter1 {
            get {
                return ResourceManager.GetString("Log_ShowCharacter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，角色名稱:  的當地語系化字串。
        /// </summary>
        internal static string Log_ShowCharacter2 {
            get {
                return ResourceManager.GetString("Log_ShowCharacter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法顯示角色資料。提供的角色ID:  的當地語系化字串。
        /// </summary>
        internal static string Log_ShowCharacterFail {
            get {
                return ResourceManager.GetString("Log_ShowCharacterFail", resourceCulture);
            }
        }
    }
}
