//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RConfig() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Forms.RConfig", typeof(RConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Beta (測試) 的當地語系化字串。
        /// </summary>
        internal static string AU_ChannelBeta {
            get {
                return ResourceManager.GetString("AU_ChannelBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stable (穩定) 的當地語系化字串。
        /// </summary>
        internal static string AU_ChannelStable {
            get {
                return ResourceManager.GetString("AU_ChannelStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只檢查和下載 的當地語系化字串。
        /// </summary>
        internal static string AU_ModeCheckAndDL {
            get {
                return ResourceManager.GetString("AU_ModeCheckAndDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只檢查 的當地語系化字串。
        /// </summary>
        internal static string AU_ModeCheckOnly {
            get {
                return ResourceManager.GetString("AU_ModeCheckOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載並自動更新 的當地語系化字串。
        /// </summary>
        internal static string AU_ModeDLAndUpdate {
            get {
                return ResourceManager.GetString("AU_ModeDLAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不檢查 的當地語系化字串。
        /// </summary>
        internal static string AU_ModeNone {
            get {
                return ResourceManager.GetString("AU_ModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔名不能為空，請選擇一個.wav檔案。 的當地語系化字串。
        /// </summary>
        internal static string Error_SelectAFile {
            get {
                return ResourceManager.GetString("Error_SelectAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於 的當地語系化字串。
        /// </summary>
        internal static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資源相關 的當地語系化字串。
        /// </summary>
        internal static string Layout_AboutData {
            get {
                return ResourceManager.GetString("Layout_AboutData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 程式自動更新 的當地語系化字串。
        /// </summary>
        internal static string Layout_AUProgram {
            get {
                return ResourceManager.GetString("Layout_AUProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 程式更新頻道 的當地語系化字串。
        /// </summary>
        internal static string Layout_AUProgramChannel {
            get {
                return ResourceManager.GetString("Layout_AUProgramChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前版本號 的當地語系化字串。
        /// </summary>
        internal static string Layout_AUProgramCurrentVersion {
            get {
                return ResourceManager.GetString("Layout_AUProgramCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新版本號 的當地語系化字串。
        /// </summary>
        internal static string Layout_AUProgramLatestVersion {
            get {
                return ResourceManager.GetString("Layout_AUProgramLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 程式檢查模式 的當地語系化字串。
        /// </summary>
        internal static string Layout_AUProgramMode {
            get {
                return ResourceManager.GetString("Layout_AUProgramMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資源檢查模式 的當地語系化字串。
        /// </summary>
        internal static string Layout_AUResourceMode {
            get {
                return ResourceManager.GetString("Layout_AUResourceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資源下載路徑(如果為空，則會下載到&quot;下載&quot;資料夾) 的當地語系化字串。
        /// </summary>
        internal static string Layout_AUResourcePath {
            get {
                return ResourceManager.GetString("Layout_AUResourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自動載入資料、資源(啟動程式時，需花費較長時間) 的當地語系化字串。
        /// </summary>
        internal static string Layout_AutoLoadText {
            get {
                return ResourceManager.GetString("Layout_AutoLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 瀏覽 的當地語系化字串。
        /// </summary>
        internal static string Layout_Browse {
            get {
                return ResourceManager.GetString("Layout_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查更新 的當地語系化字串。
        /// </summary>
        internal static string Layout_CheckUpdate {
            get {
                return ResourceManager.GetString("Layout_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 范士文 的當地語系化字串。
        /// </summary>
        internal static string Layout_DevelopersAst1 {
            get {
                return ResourceManager.GetString("Layout_DevelopersAst1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 陳嘉偉 的當地語系化字串。
        /// </summary>
        internal static string Layout_DevelopersAst2 {
            get {
                return ResourceManager.GetString("Layout_DevelopersAst2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 桐ヶ谷 水母 的當地語系化字串。
        /// </summary>
        internal static string Layout_DevelopersDev1 {
            get {
                return ResourceManager.GetString("Layout_DevelopersDev1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 協作者 的當地語系化字串。
        /// </summary>
        internal static string Layout_DevelopersTextAst {
            get {
                return ResourceManager.GetString("Layout_DevelopersTextAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開發者 的當地語系化字串。
        /// </summary>
        internal static string Layout_DevelopersTextDev {
            get {
                return ResourceManager.GetString("Layout_DevelopersTextDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 測試者 的當地語系化字串。
        /// </summary>
        internal static string Layout_DevelopersTextTst {
            get {
                return ResourceManager.GetString("Layout_DevelopersTextTst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RaenonX JELLYCAT 的當地語系化字串。
        /// </summary>
        internal static string Layout_DevelopersTst1 {
            get {
                return ResourceManager.GetString("Layout_DevelopersTst1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 靜音 的當地語系化字串。
        /// </summary>
        internal static string Layout_Mute {
            get {
                return ResourceManager.GetString("Layout_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 按鍵聲 的當地語系化字串。
        /// </summary>
        internal static string Layout_PathBeep {
            get {
                return ResourceManager.GetString("Layout_PathBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BGM 的當地語系化字串。
        /// </summary>
        internal static string Layout_PathBGM {
            get {
                return ResourceManager.GetString("Layout_PathBGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息音 的當地語系化字串。
        /// </summary>
        internal static string Layout_PathMessage {
            get {
                return ResourceManager.GetString("Layout_PathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警示音 的當地語系化字串。
        /// </summary>
        internal static string Layout_PathWarning {
            get {
                return ResourceManager.GetString("Layout_PathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尋找資料位置 的當地語系化字串。
        /// </summary>
        internal static string Layout_ReadTitle {
            get {
                return ResourceManager.GetString("Layout_ReadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 音效 的當地語系化字串。
        /// </summary>
        internal static string Layout_SEGroupBox {
            get {
                return ResourceManager.GetString("Layout_SEGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版本資訊 的當地語系化字串。
        /// </summary>
        internal static string Layout_VersionText {
            get {
                return ResourceManager.GetString("Layout_VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開啟路徑選擇對話框。對話框敘述:  的當地語系化字串。
        /// </summary>
        internal static string Log_StartChooseDirectory {
            get {
                return ResourceManager.GetString("Log_StartChooseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇要存放 的當地語系化字串。
        /// </summary>
        internal static string Message_ChoosePathToStoreFile1 {
            get {
                return ResourceManager.GetString("Message_ChoosePathToStoreFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 的資料夾位置。 的當地語系化字串。
        /// </summary>
        internal static string Message_ChoosePathToStoreFile2 {
            get {
                return ResourceManager.GetString("Message_ChoosePathToStoreFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 csv資源檔 的當地語系化字串。
        /// </summary>
        internal static string Message_Csv {
            get {
                return ResourceManager.GetString("Message_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否下載？ 的當地語系化字串。
        /// </summary>
        internal static string Message_DownloadOrNot {
            get {
                return ResourceManager.GetString("Message_DownloadOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 程式 的當地語系化字串。
        /// </summary>
        internal static string Message_Program {
            get {
                return ResourceManager.GetString("Message_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 程式資源檔 的當地語系化字串。
        /// </summary>
        internal static string Message_Resource {
            get {
                return ResourceManager.GetString("Message_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有可用的更新！ 的當地語系化字串。
        /// </summary>
        internal static string Message_UpdateAvailable {
            get {
                return ResourceManager.GetString("Message_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前版本:  的當地語系化字串。
        /// </summary>
        internal static string Message_VersionCurrent {
            get {
                return ResourceManager.GetString("Message_VersionCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，最新版本:  的當地語系化字串。
        /// </summary>
        internal static string Message_VersionNew {
            get {
                return ResourceManager.GetString("Message_VersionNew", resourceCulture);
            }
        }
    }
}
