//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RDownload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RDownload() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Forms.RDownload", typeof(RDownload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 取消下載 的當地語系化字串。
        /// </summary>
        internal static string DL_AbortDownload {
            get {
                return ResourceManager.GetString("DL_AbortDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        internal static string Layout_Add {
            get {
                return ResourceManager.GetString("Layout_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增全部 的當地語系化字串。
        /// </summary>
        internal static string Layout_AddAll {
            get {
                return ResourceManager.GetString("Layout_AddAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始下載 的當地語系化字串。
        /// </summary>
        internal static string Layout_BeginDL {
            get {
                return ResourceManager.GetString("Layout_BeginDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色ID 的當地語系化字串。
        /// </summary>
        internal static string Layout_CharaID {
            get {
                return ResourceManager.GetString("Layout_CharaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色圖片下載 的當地語系化字串。
        /// </summary>
        internal static string Layout_CharaPicDL {
            get {
                return ResourceManager.GetString("Layout_CharaPicDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清除全部 的當地語系化字串。
        /// </summary>
        internal static string Layout_ClearAll {
            get {
                return ResourceManager.GetString("Layout_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已下載圖片 的當地語系化字串。
        /// </summary>
        internal static string Layout_Complete {
            get {
                return ResourceManager.GetString("Layout_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載結果 的當地語系化字串。
        /// </summary>
        internal static string Layout_CompleteList {
            get {
                return ResourceManager.GetString("Layout_CompleteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載中圖片 的當地語系化字串。
        /// </summary>
        internal static string Layout_Downloading {
            get {
                return ResourceManager.GetString("Layout_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載清單 的當地語系化字串。
        /// </summary>
        internal static string Layout_DownloadList {
            get {
                return ResourceManager.GetString("Layout_DownloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載日誌 的當地語系化字串。
        /// </summary>
        internal static string Layout_DownloadLog {
            get {
                return ResourceManager.GetString("Layout_DownloadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載失敗 的當地語系化字串。
        /// </summary>
        internal static string Layout_Failed {
            get {
                return ResourceManager.GetString("Layout_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待下載圖片 的當地語系化字串。
        /// </summary>
        internal static string Layout_Pending {
            get {
                return ResourceManager.GetString("Layout_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖片數量 的當地語系化字串。
        /// </summary>
        internal static string Layout_PicCount {
            get {
                return ResourceManager.GetString("Layout_PicCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 移除 的當地語系化字串。
        /// </summary>
        internal static string Layout_Remove {
            get {
                return ResourceManager.GetString("Layout_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始下載角色圖片。角色總量:  的當地語系化字串。
        /// </summary>
        internal static string Log_BeginDownload {
            get {
                return ResourceManager.GetString("Log_BeginDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立角色圖片下載器，角色ID:  的當地語系化字串。
        /// </summary>
        internal static string Log_BuildDownloader {
            get {
                return ResourceManager.GetString("Log_BuildDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已取消角色下載作業。未完成下載的圖片將刪除，已下載完畢的圖片將會續留。角色總數: 的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadCancelled_1 {
            get {
                return ResourceManager.GetString("Log_DownloadCancelled_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，已下載:  的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadCancelled_2 {
            get {
                return ResourceManager.GetString("Log_DownloadCancelled_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 \n檔案儲存路徑:  的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadCancelled_3 {
            get {
                return ResourceManager.GetString("Log_DownloadCancelled_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色全部下載完成。角色總數:  的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadComplete_1 {
            get {
                return ResourceManager.GetString("Log_DownloadComplete_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，下載成功:  的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadComplete_2 {
            get {
                return ResourceManager.GetString("Log_DownloadComplete_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，下載失敗:  的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadComplete_3 {
            get {
                return ResourceManager.GetString("Log_DownloadComplete_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 \n檔案儲存路徑:  的當地語系化字串。
        /// </summary>
        internal static string Log_DownloadComplete_4 {
            get {
                return ResourceManager.GetString("Log_DownloadComplete_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開啟已下載的檔案:  的當地語系化字串。
        /// </summary>
        internal static string Log_OpenFile {
            get {
                return ResourceManager.GetString("Log_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 於檔案下載中開啟角色系代碼表。 的當地語系化字串。
        /// </summary>
        internal static string Log_OpenSeriesTable {
            get {
                return ResourceManager.GetString("Log_OpenSeriesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刷新角色圖片下載進度。總進度:  的當地語系化字串。
        /// </summary>
        internal static string Log_RefreshStatus_1 {
            get {
                return ResourceManager.GetString("Log_RefreshStatus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 %，待下載:  的當地語系化字串。
        /// </summary>
        internal static string Log_RefreshStatus_2 {
            get {
                return ResourceManager.GetString("Log_RefreshStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，下載中:  的當地語系化字串。
        /// </summary>
        internal static string Log_RefreshStatus_3 {
            get {
                return ResourceManager.GetString("Log_RefreshStatus_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，已下載:  的當地語系化字串。
        /// </summary>
        internal static string Log_RefreshStatus_4 {
            get {
                return ResourceManager.GetString("Log_RefreshStatus_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，下載失敗:  的當地語系化字串。
        /// </summary>
        internal static string Log_RefreshStatus_5 {
            get {
                return ResourceManager.GetString("Log_RefreshStatus_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要清除所有在下載清單中的角色嗎？ 的當地語系化字串。
        /// </summary>
        internal static string Message_EnsureClear {
            get {
                return ResourceManager.GetString("Message_EnsureClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案存放路徑:  的當地語系化字串。
        /// </summary>
        internal static string Message_FilePath {
            get {
                return ResourceManager.GetString("Message_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否開啟檔案總管並導引至檔案存放路徑？ 的當地語系化字串。
        /// </summary>
        internal static string Message_OpenFilePath {
            get {
                return ResourceManager.GetString("Message_OpenFilePath", resourceCulture);
            }
        }
    }
}
