//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RExpCalc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RExpCalc() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Forms.RExpCalc", typeof(RExpCalc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 訓練後 的當地語系化字串。
        /// </summary>
        internal static string Layout_After {
            get {
                return ResourceManager.GetString("Layout_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訓練前 的當地語系化字串。
        /// </summary>
        internal static string Layout_Before {
            get {
                return ResourceManager.GetString("Layout_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 計算 的當地語系化字串。
        /// </summary>
        internal static string Layout_Calc {
            get {
                return ResourceManager.GetString("Layout_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 普通角色 的當地語系化字串。
        /// </summary>
        internal static string Layout_Chara {
            get {
                return ResourceManager.GetString("Layout_Chara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 COST 的當地語系化字串。
        /// </summary>
        internal static string Layout_Cost {
            get {
                return ResourceManager.GetString("Layout_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 剩餘經驗 的當地語系化字串。
        /// </summary>
        internal static string Layout_ExpLeft {
            get {
                return ResourceManager.GetString("Layout_ExpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 經驗需求 的當地語系化字串。
        /// </summary>
        internal static string Layout_ExpNeed {
            get {
                return ResourceManager.GetString("Layout_ExpNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HP 的當地語系化字串。
        /// </summary>
        internal static string Layout_HP {
            get {
                return ResourceManager.GetString("Layout_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 INT 的當地語系化字串。
        /// </summary>
        internal static string Layout_INT {
            get {
                return ResourceManager.GetString("Layout_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色等級 的當地語系化字串。
        /// </summary>
        internal static string Layout_Lv {
            get {
                return ResourceManager.GetString("Layout_Lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主角/主人公 的當地語系化字串。
        /// </summary>
        internal static string Layout_Main {
            get {
                return ResourceManager.GetString("Layout_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MEN 的當地語系化字串。
        /// </summary>
        internal static string Layout_MEN {
            get {
                return ResourceManager.GetString("Layout_MEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SS Power 的當地語系化字串。
        /// </summary>
        internal static string Layout_SS {
            get {
                return ResourceManager.GetString("Layout_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 STR 的當地語系化字串。
        /// </summary>
        internal static string Layout_STR {
            get {
                return ResourceManager.GetString("Layout_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VIT 的當地語系化字串。
        /// </summary>
        internal static string Layout_VIT {
            get {
                return ResourceManager.GetString("Layout_VIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 由Lv.01到Lv.60(五星滿等)需要79791經驗；由Lv.01到Lv.70(六星滿等)需要110292經驗；由Lv.01~Lv.80需要145991經驗。 的當地語系化字串。
        /// </summary>
        internal static string Message_FastTip {
            get {
                return ResourceManager.GetString("Message_FastTip", resourceCulture);
            }
        }
    }
}
