//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAOCR_Data_Manager.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RMessageBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RMessageBox() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAOCR_Data_Manager.Resources.Forms.RMessageBox", typeof(RMessageBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        internal static string Cmd_Cancel {
            get {
                return ResourceManager.GetString("Cmd_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 的當地語系化字串。
        /// </summary>
        internal static string Cmd_Download {
            get {
                return ResourceManager.GetString("Cmd_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 安裝 的當地語系化字串。
        /// </summary>
        internal static string Cmd_Install {
            get {
                return ResourceManager.GetString("Cmd_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        internal static string Cmd_No {
            get {
                return ResourceManager.GetString("Cmd_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認 的當地語系化字串。
        /// </summary>
        internal static string Cmd_OK {
            get {
                return ResourceManager.GetString("Cmd_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新啟動 的當地語系化字串。
        /// </summary>
        internal static string Cmd_Restart {
            get {
                return ResourceManager.GetString("Cmd_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重試 的當地語系化字串。
        /// </summary>
        internal static string Cmd_Retry {
            get {
                return ResourceManager.GetString("Cmd_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        internal static string Cmd_Yes {
            get {
                return ResourceManager.GetString("Cmd_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總共有  的當地語系化字串。
        /// </summary>
        internal static string Layout_DownloadItems1 {
            get {
                return ResourceManager.GetString("Layout_DownloadItems1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  個項目要下載。目前進度:  的當地語系化字串。
        /// </summary>
        internal static string Layout_DownloadItems2 {
            get {
                return ResourceManager.GetString("Layout_DownloadItems2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 容量:  的當地語系化字串。
        /// </summary>
        internal static string Layout_Size {
            get {
                return ResourceManager.GetString("Layout_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 速度:  的當地語系化字串。
        /// </summary>
        internal static string Layout_Speed {
            get {
                return ResourceManager.GetString("Layout_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 警告 的當地語系化字串。
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
    }
}
